"""
Grammar Playground - Parser Generator
Generates recursive descent and table-driven parsers
"""

from typing import List, Dict, Set, Optional
from .grammar import Grammar, Symbol, Production, EPSILON, END_MARKER
from .ll1_analyzer import LL1Analyzer, LL1Table


class RecursiveDescentGenerator:
    """Generates a recursive descent parser from an LL(1) grammar"""
    
    def __init__(self, grammar: Grammar, analyzer: LL1Analyzer):
        self.grammar = grammar
        self.analyzer = analyzer
        if not analyzer.ll1_table:
            analyzer.analyze()
    
    def generate(self, language: str = "python") -> str:
        """Generate parser code in Python"""
        if language.lower() == "python":
            return self._generate_python()
        else:
            raise ValueError(f"Unsupported language: {language} (only Python is supported)")
    
    def _generate_python(self) -> str:
        """Generate simple academic-style Python recursive descent parser.
        
        Output uses:
        - Global variables: tokens (list), pos (int)
        - Helper functions: match(), lookahead(), error()
        - Parsing functions: parse_Symbol() returns nested tuples
        - No classes or complex OOP
        """
        lines = [
            '"""',
            'Recursive Descent Parser - Academic Style',
            'Generated by Grammar Playground',
            '"""',
            '',
            '# Global state',
            'tokens = []  # List of token strings to parse',
            'pos = 0      # Current position in tokens list',
            '',
            '',
            'class ParseError(Exception):',
            '    """Exception raised when parsing fails"""',
            '    pass',
            '',
            '',
            'def error(expected: str) -> None:',
            '    """Raise a parse error with a helpful message"""',
            '    global pos, tokens',
            '    current = tokens[pos] if pos < len(tokens) else "$"',
            f'    raise ParseError(f"Expected {{expected}} but got {{current}} at position {{pos}}")',
            '',
            '',
            'def lookahead() -> str:',
            '    """Look at the current token without consuming it"""',
            '    global tokens, pos',
            '    if pos < len(tokens):',
            '        return tokens[pos]',
            '    return "$"  # End-of-input marker',
            '',
            '',
            'def match(expected: str) -> str:',
            '    """Match and consume a terminal token"""',
            '    global pos, tokens',
            '    if pos < len(tokens) and tokens[pos] == expected:',
            '        token = tokens[pos]',
            '        pos += 1',
            '        return token',
            '    error(expected)',
            '',
        ]
        
        # Generate parsing function for each non-terminal
        for nt in sorted(self.grammar.non_terminals, key=lambda x: str(x)):
            lines.extend(self._generate_nt_method_python(nt))
            lines.append('')
        
        # Add main parse function
        start_name = self._safe_name(str(self.grammar.start_symbol))
        lines.extend([
            f'def parse(input_tokens: list):',
            f'    """Parse the input tokens starting from {self.grammar.start_symbol}"""',
            f'    global tokens, pos',
            f'    tokens = input_tokens',
            f'    pos = 0',
            f'    tree = {start_name}()',
            f'    if pos < len(tokens):',
            f'        error("end of input")',
            f'    return tree',
            '',
        ])
        
        return '\n'.join(lines)
    
    def _generate_nt_method_python(self, nt: Symbol) -> List[str]:
        """Generate a simple parsing function for a non-terminal.
        
        Returns nested tuples representing the parse tree:
          parse_Expr() -> ('Expr', parse_Term(), parse_Expr_Prime())
        
        No classes, no state manipulation - just clean recursive functions.
        """
        safe_name = self._safe_name(str(nt))
        productions = self.grammar.get_productions_for(nt)
        
        lines = [
            f'def {safe_name}():',
            f'    """Parse {nt} non-terminal"""',
            f'    la = lookahead()',
            f'    children = []',
            f'',
        ]
        
        # Build FIRST/FOLLOW cases
        cases = []
        for prod in productions:
            first_set = self.analyzer.first_of_production(prod)
            terminals = [str(t) for t in first_set if t != EPSILON]
            
            is_nullable = EPSILON in first_set
            if is_nullable:
                follow_terminals = [str(t) for t in self.analyzer.follow(nt)]
                cases.append((follow_terminals, prod, True))
            else:
                cases.append((terminals, prod, False))
        
        # Generate if-elif chain for lookahead dispatch
        is_first = True
        for terminals, prod, is_nullable in cases:
            term_list = ", ".join(f'"{t}"' for t in terminals)
            condition = f"la in [{term_list}]" if terminals else "True"
            
            if is_first:
                lines.append(f"    if {condition}:")
                is_first = False
            else:
                lines.append(f"    elif {condition}:")
            
            # Generate code for this production
            lines.append(f"        # {prod}")
            
            if prod.is_epsilon_production():
                # Epsilon production: just return the non-terminal with no children
                lines.append(f"        pass")
            else:
                # Build up children list for non-epsilon productions
                for symbol in prod.body:
                    if symbol.is_epsilon():
                        continue  # Epsilon doesn't generate anything
                    elif symbol.is_terminal():
                        lines.append(f"        children.append(match('{symbol}'))  # Terminal: {symbol}")
                    else:
                        # Non-terminal: recursive call
                        child_name = self._safe_name(str(symbol))
                        lines.append(f"        children.append({child_name}())  # Non-terminal: {symbol}")
        
        # Add error case if needed
        all_terminals = set()
        for terminals, _, _ in cases:
            all_terminals.update(terminals)
        
        if all_terminals:
            expected = " or ".join(sorted(all_terminals))
            if not is_first:
                lines.append(f"    else:")
                lines.append(f"        error('{expected}')")
        
        # Return the parse tree as a nested tuple
        lines.append(f"    return (\"{nt}\", *children)")
        
        return lines
    

    
    def _safe_name(self, name: str) -> str:
        """Convert a symbol name to a safe Python identifier"""
        result = name.replace("'", "_prime").replace("-", "_")
        result = ''.join(c if c.isalnum() or c == '_' else '_' for c in result)
        return result.lower()



class TableDrivenGenerator:
    """Generates a table-driven LL(1) parser"""
    
    def __init__(self, grammar: Grammar, analyzer: LL1Analyzer):
        self.grammar = grammar
        self.analyzer = analyzer
        if not analyzer.ll1_table:
            analyzer.analyze()
    
    def generate(self, language: str = "python") -> str:
        """Generate table-driven parser code"""
        if language.lower() == "python":
            return self._generate_python()
        else:
            raise ValueError(f"Unsupported language: {language}")
    
    def _generate_python(self) -> str:
        """Generate Python table-driven parser"""
        # Build table data
        table_entries = []
        for (nt, terminal), productions in self.analyzer.ll1_table.table.items():
            if productions:
                prod = productions[0]
                body = [str(s) for s in prod.body]
                table_entries.append(f'    ("{nt}", "{terminal}"): {body},')
        
        # Get all terminals and non-terminals
        terminals = sorted([str(t) for t in self.grammar.terminals])
        non_terminals = sorted([str(nt) for nt in self.grammar.non_terminals])
        
        code = f'''"""
Table-Driven LL(1) Parser
Generated by Grammar Playground
"""

from typing import List, Optional, Tuple, Dict


class ParseError(Exception):
    """Raised when parsing fails"""
    pass


class Token:
    """Represents a token from the lexer"""
    def __init__(self, type: str, value: str, pos: int = 0):
        self.type = type
        self.value = value
        self.pos = pos
    
    def __repr__(self):
        return f"Token({{self.type}}, {{self.value!r}})"


class ParseTreeNode:
    """Node in the parse tree"""
    def __init__(self, symbol: str, children: List["ParseTreeNode"] = None, token: Token = None):
        self.symbol = symbol
        self.children = children or []
        self.token = token
    
    def is_terminal(self) -> bool:
        return self.token is not None
    
    def add_child(self, child: "ParseTreeNode"):
        self.children.append(child)


# Grammar information
TERMINALS = {terminals}
NON_TERMINALS = {non_terminals}
START_SYMBOL = "{self.grammar.start_symbol}"

# LL(1) Parsing Table
# Key: (non_terminal, terminal) -> production body as list of symbols
PARSE_TABLE: Dict[Tuple[str, str], List[str]] = {{
{chr(10).join(table_entries)}
}}


class TableDrivenParser:
    """Table-Driven LL(1) Parser"""
    
    def __init__(self, tokens: List[Token]):
        self.tokens = tokens
        self.pos = 0
        self.current_token: Optional[Token] = tokens[0] if tokens else None
    
    def lookahead(self) -> str:
        """Return the type of the current token"""
        if self.current_token:
            return self.current_token.type
        return "$"
    
    def advance(self) -> Token:
        """Move to the next token"""
        token = self.current_token
        self.pos += 1
        if self.pos < len(self.tokens):
            self.current_token = self.tokens[self.pos]
        else:
            self.current_token = None
        return token
    
    def parse(self) -> ParseTreeNode:
        """Parse the input using the LL(1) table"""
        # Stack contains (symbol, parent_node) pairs
        root = ParseTreeNode(START_SYMBOL)
        stack: List[Tuple[str, ParseTreeNode]] = [("$", None), (START_SYMBOL, root)]
        
        while stack:
            top_symbol, parent = stack.pop()
            la = self.lookahead()
            
            if top_symbol == "$":
                if la == "$":
                    break
                else:
                    raise ParseError(f"Expected end of input but got {{la}}")
            
            if top_symbol == "ε":
                # Epsilon - do nothing
                continue
            
            if top_symbol in TERMINALS:
                # Terminal - must match
                if top_symbol == la:
                    token = self.advance()
                    if parent:
                        parent.children.append(ParseTreeNode(top_symbol, token=token))
                else:
                    raise ParseError(f"Expected {{top_symbol}} but got {{la}}")
            
            elif top_symbol in NON_TERMINALS:
                # Non-terminal - consult the table
                key = (top_symbol, la)
                if key not in PARSE_TABLE:
                    raise ParseError(f"No production for {{top_symbol}} with lookahead {{la}}")
                
                production_body = PARSE_TABLE[key]
                
                # Create a node for this non-terminal
                node = ParseTreeNode(top_symbol)
                if parent:
                    parent.children.append(node)
                
                # Push production body in reverse order
                for symbol in reversed(production_body):
                    stack.append((symbol, node))
            
            else:
                raise ParseError(f"Unknown symbol: {{top_symbol}}")
        
        return root


def tokenize_simple(text: str) -> List[Token]:
    """Simple tokenizer for testing - splits on whitespace"""
    tokens = []
    pos = 0
    for word in text.split():
        tokens.append(Token(word, word, pos))
        pos += len(word) + 1
    return tokens


if __name__ == "__main__":
    # Example usage
    test_input = "your input here"
    tokens = tokenize_simple(test_input)
    parser = TableDrivenParser(tokens)
    try:
        tree = parser.parse()
        print("Parse successful!")
        print(tree)
    except ParseError as e:
        print(f"Parse error: {{e}}")
'''
        return code
